NaniWeb/Controllers/ChapterManagerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NaniWeb.Data;
using NaniWeb.Models.Chapter;
using NaniWeb.Others;
using NaniWeb.Others.Services;

namespace NaniWeb.Controllers
{
    public class ChapterManagerController : Controller
    {
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly NaniWebContext _naniWebContext;
        private readonly SettingsManager _settingsManager;

        public ChapterManagerController(IWebHostEnvironment hostingEnvironment, NaniWebContext naniWebContext, SettingsManager settingsManager)
        {
            _hostingEnvironment = hostingEnvironment;
            _naniWebContext = naniWebContext;
            _settingsManager = settingsManager;
        }

        [Authorize(Roles = "Administrator, Moderator, Uploader")]
        public async Task<IActionResult> List(int id)
        {
            var chapters = await _naniWebContext.Chapters.Where(chp => chp.SeriesId == id).OrderByDescending(key => key.ChapterNumber).ToArrayAsync();

            ViewData["Chapters"] = chapters;

            return View("ChapterList");
        }

        [HttpGet]
        [Authorize(Roles = "Administrator, Moderator, Uploader")]
        public async Task<IActionResult> Add(int id)
        {
            var series = await _naniWebContext.Series.SingleAsync(srs => srs.Id == id);

            ViewData["SeriesName"] = series.Name;
            var model = new ChapterAdd
            {
                SeriesId = series.Id
            };

            return View("AddChapter", model);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator, Moderator, Uploader")]
        [RequestSizeLimit(100000000)]
        public async Task<IActionResult> Add(ChapterAdd chapterAdd)
        {
            if (ModelState.IsValid)
            {
                var series = await _naniWebContext.Series.SingleAsync(srs => srs.Id == chapterAdd.SeriesId);
                var chapter = new Chapter
                {
                    Volume = chapterAdd.Volume ?? 0,
                    ChapterNumber = chapterAdd.ChapterNumber,
                    Name = chapterAdd.Name ?? string.Empty,
                    SeriesId = series.Id,
                    Pages = new List<Page>(),
                    ReleaseDate = DateTime.UtcNow
                };

                var temp = Utils.CurrentDirectory.CreateSubdirectory($"Temp{Path.DirectorySeparatorChar}{Guid.NewGuid()}");
                var tempPages = temp.CreateSubdirectory("Pages");
                var destination = $"{_hostingEnvironment.WebRootPath}{Path.DirectorySeparatorChar}images{Path.DirectorySeparatorChar}pages{Path.DirectorySeparatorChar}";
                var pagesZip = $"{temp.FullName}{Path.DirectorySeparatorChar}pages.zip";
                Directory.CreateDirectory(destination);

                using (var stream = System.IO.File.Create(pagesZip))
                {
                    await chapterAdd.Pages.CopyToAsync(stream);
                }

                ZipFile.ExtractToDirectory(pagesZip, tempPages.FullName);
                var pageList = tempPages.EnumerateFiles().Where(fl => fl.Extension == ".png").OrderBy(fl => fl.Name.Length).ThenBy(fl => fl.Name).ToList();

                if (pageList.Count == 0)
                {
                    temp.Delete(true);

                    TempData["Error"] = true;

                    return RedirectToAction("Add");
                }

                for (var i = 0; i < pageList.Count; i++)
                {
                    var page = new Page
                    {
                        PageNumber = i
                    };

                    do
                    {
                        page.Id = Guid.NewGuid();
                    } while (System.IO.File.Exists($"{destination}{page.Id}.png"));

                    chapter.Pages.Add(page);

                    pageList[i].CopyTo($"{destination}{page.Id}.png");
                }

                await _naniWebContext.Chapters.AddAsync(chapter);
                await _naniWebContext.SaveChangesAsync();

                temp.Delete(true);

                return RedirectToAction("List", "SeriesManager", new {id = series.Id});
            }

            TempData["Error"] = true;

            return RedirectToAction("Add");
        }

        [HttpGet]
        [Authorize(Roles = "Administrator, Moderator")]
        public async Task<IActionResult> Edit(int id)
        {
            var chapter = await _naniWebContext.Chapters.SingleAsync(chp => chp.Id == id);
            var model = new ChapterEdit
            {
                ChapterId = chapter.Id,
                Volume = chapter.Volume,
                ChapterNumber = chapter.ChapterNumber,
                Name = chapter.Name,
            };

            return View("EditChapter", model);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator, Moderator")]
        [RequestSizeLimit(100000000)]
        public async Task<IActionResult> Edit(ChapterEdit chapterEdit)
        {
            if (ModelState.IsValid)
            {
                var chapter = await _naniWebContext.Chapters.SingleAsync(chp => chp.Id == chapterEdit.ChapterId);
                chapter.Volume = chapterEdit.Volume ?? 0;
                chapter.ChapterNumber = chapterEdit.ChapterNumber;
                chapter.Name = chapterEdit.Name ?? string.Empty;

                if (chapterEdit.Pages != null)
                {
                    var temp = Utils.CurrentDirectory.CreateSubdirectory($"Temp{Path.DirectorySeparatorChar}{Guid.NewGuid()}");
                    var tempPages = temp.CreateSubdirectory("Pages");
                    var destination = $"{_hostingEnvironment.WebRootPath}{Path.DirectorySeparatorChar}images{Path.DirectorySeparatorChar}pages{Path.DirectorySeparatorChar}";
                    var pagesZip = $"{temp.FullName}{Path.DirectorySeparatorChar}pages.zip";
                    var pages = _naniWebContext.Pages.Where(pg => pg.Chapter == chapter);
                    var downloadsDir = Utils.CurrentDirectory.CreateSubdirectory("Downloads");
                    var downloadFile = $"{downloadsDir.FullName}{Path.DirectorySeparatorChar}{chapter.Id}.zip";

                    foreach (var page in pages)
                        System.IO.File.Delete($"{destination}{page.Id}.png");

                    _naniWebContext.Pages.RemoveRange(pages);

                    using (var stream = System.IO.File.Create(pagesZip))
                    {
                        await chapterEdit.Pages.CopyToAsync(stream);
                    }

                    ZipFile.ExtractToDirectory(pagesZip, tempPages.FullName);
                    var pageList = tempPages.EnumerateFiles().Where(fl => fl.Extension == ".png").OrderBy(fl => fl.Name.Length).ThenBy(fl => fl.Name).ToList();
                    chapter.Pages = new List<Page>();


                    for (var i = 0; i < pageList.Count; i++)
                    {
                        var page = new Page
                        {
                            PageNumber = i
                        };

                        do
                        {
                            page.Id = Guid.NewGuid();
                        } while (System.IO.File.Exists($"{destination}{page.Id}.png"));

                        chapter.Pages.Add(page);

                        pageList[i].CopyTo($"{destination}{page.Id}.png");

                        System.IO.File.Delete(downloadFile);
                    }

                    temp.Delete(true);
                }

                _naniWebContext.Chapters.Update(chapter);
                await _naniWebContext.SaveChangesAsync();

                return RedirectToAction("List", new {id = chapter.SeriesId});
            }

            TempData["Error"] = true;

            return RedirectToAction("Add");
        }

        [Authorize(Roles = "Administrator, Moderator")]
        public async Task<IActionResult> Delete(int id)
        {
            var chapter = await _naniWebContext.Chapters.Include(chp => chp.Pages).SingleAsync(chp => chp.Id == id);
            var series = await _naniWebContext.Series.SingleAsync(srs => srs.Id == chapter.SeriesId);
            var destination = $"{_hostingEnvironment.WebRootPath}{Path.DirectorySeparatorChar}images{Path.DirectorySeparatorChar}pages{Path.DirectorySeparatorChar}";
            var downloadsDir = Utils.CurrentDirectory.CreateSubdirectory("Downloads");
            var file = $"{downloadsDir.FullName}{Path.DirectorySeparatorChar}{chapter.Id}.zip";

            foreach (var page in chapter.Pages)
                System.IO.File.Delete($"{destination}{page.Id}.png");

            System.IO.File.Delete(file);

            _naniWebContext.Chapters.Remove(chapter);
            await _naniWebContext.SaveChangesAsync();

            return RedirectToAction("List", new {id = series.Id});
        }
    }
}

NaniWeb/Views/ChapterManager/AddChapter.cshtml
@model ChapterAdd

@{
    ViewData["Title"] = "Add - Chapter";
}

<partial name="_AdminNav"/>

<div class="container mt-3">
    <div class="card bg-primary border-secondary">
        <h5 class="card-header bg-primary">Chapters</h5>
        <div class="card-body">
            @if (TempData["Error"] != null && (bool) TempData["Error"])
            {
                <div class="alert alert-dismissible alert-danger">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Something went wrong. Please check your data and try again.
                </div>
            }
            <form id="add_chapter_form" enctype="multipart/form-data" asp-controller="ChapterManager" asp-action="Add" novalidate>
                <fieldset>
                    <legend>Add Chapter</legend>
                    <input type="hidden" asp-for="SeriesId"/>
                    <div class="form-group">
                        <label for="series_name">Series</label>
                        <input class="form-control" id="series_name" asp-for="@ViewData["SeriesName"]" disabled>
                    </div>
                    <div class="form-group">
                        <label for="chapter_volume">Volume</label>
                        <input class="form-control" id="chapter_volume" asp-for="Volume" aria-describedby="chapter_volume_help" placeholder="Volume">
                        <small id="chapter_volume_help" class="form-text text-muted">If this chapter is part of a volume add it here, otherwise keep it zero or empty.</small>
                    </div>
                    <div class="form-group">
                        <label for="chapter_number">Chapter Number</label>
                        <input class="form-control" id="chapter_number" asp-for="ChapterNumber" aria-describedby="chapter_number_help" placeholder="Chapter Number" type="number" step="0.01">
                        <small id="chapter_number_help" class="form-text text-muted">The number of this chapter.</small>
                    </div>
                    <div class="form-group">
                        <label for="chapter_name">Name</label>
                        <input class="form-control" id="chapter_name" asp-for="Name" aria-describedby="chapter_name_help" placeholder="Name">
                        <small id="chapter_name_help" class="form-text text-muted">The name of this chapter.</small>
                    </div>
                    <div class="form-group">
                        <div class="input-group" aria-describedby="chapter_pages_help">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="chapter_pages" accept=".zip" asp-for="Pages">
                                <label class="custom-file-label" for="chapter_pages" id="chapter_pages_label">Choose File</label>
                            </div>
                        </div>
                        <small id="chapter_pages_help" class="form-text text-muted">A zip file with all pages. The pages must be in the PNG format.</small>
                    </div>
                </fieldset>
                <div>
                    <button class="btn btn-success float-right mt-3" id="submit" type="submit">Add Chapter</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Body
{
    <script>
        $("#series").addClass("active");

        $("#chapter_pages").change(function(event) {
            const file = event.target.files[0].name;
            $("#chapter_pages_label").text(file);
        });
    </script>
}

NaniWeb/Views/ChapterManager/ChapterList.cshtml
@using NaniWeb.Data
@{
    ViewData["Title"] = "Chapters";
    var chapters = (Chapter[]) ViewData["Chapters"];
}

<partial name="_AdminNav"/>

<div class="container mt-3">
    <div class="card bg-primary border-secondary">
        <h5 class="card-header bg-primary">Chapters</h5>
        <div class="card-body">
            @if (chapters.Length > 0)
            {
                foreach (var chapter in chapters)
                {
                    <div class="row mb-1">
                        <div class="col-8 my-auto text-center text-truncate">
                            @(chapter.Volume > 0 ? $"Vol. {chapter.Volume} " : string.Empty)Ch. @(chapter.ChapterNumber)@(string.IsNullOrEmpty(chapter.Name) ? string.Empty : $" - {chapter.Name}")
                        </div>
                        <div class="col-4 px-0 text-center">
                            <div class="dropdown">
                                <button class="btn btn-sm btn-info dropdown-toggle" type="button" id="actions_drop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Actions
                                </button>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="actions_drop">
                                    <a class="dropdown-item" href="@Url.Action("Edit", new {id = chapter.Id})">Edit</a>
                                    <a class="dropdown-item delete-chapter" href="@Url.Action("Delete", new {id = chapter.Id})">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="text-center">
                    <h3>No chapters found.</h3>
                </div>
            }
        </div>
    </div>
    <div id="delete_modal" class="modal text-dark">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Are you sure?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure that you want to permanently delete this chapter?</p>
                </div>
                <div class="modal-footer">
                    <button id="confirm_delete" type="button" class="btn btn-danger">Delete</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section Body
{
    <script>
        var address = null;

        $("#series").addClass("active");

        $(".delete-chapter").click(function(event) {
            event.preventDefault();
            $("#delete_modal").modal("show");
            address = $(this).attr("href");
        });

        $("#confirm_delete").click(function() {
            window.location = address;
        });
    </script>
}

NaniWeb/Views/ChapterManager/EditChapter.cshtml
@model ChapterEdit

@{
    ViewData["Title"] = "Edit - Chapter";
}

<partial name="_AdminNav"/>

<div class="container mt-3">
    <div class="card bg-primary border-secondary">
        <h5 class="card-header bg-primary">Chapters</h5>
        <div class="card-body">
            @if (TempData["Error"] != null && (bool) TempData["Error"])
            {
                <div class="alert alert-dismissible alert-danger">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Something went wrong. Please check your data and try again.
                </div>
            }
            <form id="edit_chapter_form" enctype="multipart/form-data" asp-controller="ChapterManager" asp-action="Edit" novalidate>
                <fieldset>
                    <legend>Edit Chapter</legend>
                    <input type="hidden" asp-for="ChapterId"/>
                    <div class="form-group">
                        <label for="chapter_volume">Volume</label>
                        <input class="form-control" id="chapter_volume" asp-for="Volume" aria-describedby="chapter_volume_help" placeholder="Volume">
                        <small id="chapter_volume_help" class="form-text text-muted">If this chapter is part of a volume add it here, otherwise keep it zero or empty.</small>
                    </div>
                    <div class="form-group">
                        <label for="chapter_number">Chapter Number</label>
                        <input class="form-control" id="chapter_number" asp-for="ChapterNumber" aria-describedby="chapter_number_help" placeholder="Chapter Number" type="number" step="0.01">
                        <small id="chapter_number_help" class="form-text text-muted">The number of this chapter.</small>
                    </div>
                    <div class="form-group">
                        <label for="chapter_name">Name</label>
                        <input class="form-control" id="chapter_name" asp-for="Name" aria-describedby="chapter_name_help" placeholder="Name">
                        <small id="chapter_name_help" class="form-text text-muted">The name of this chapter.</small>
                    </div>
                    <div class="form-group">
                        <div class="input-group" aria-describedby="chapter_pages_help">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="chapter_pages" accept=".zip" asp-for="Pages">
                                <label class="custom-file-label" for="chapter_pages" id="chapter_pages_label">Choose File</label>
                            </div>
                        </div>
                        <small id="chapter_pages_help" class="form-text text-muted">A zip file with all pages. The pages must be in the PNG format.</small>
                    </div>
                </fieldset>
                <div>
                    <button class="btn btn-success float-right mt-3" id="submit" type="submit">Save Edits</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Body
{
    <script>
        $("#series").addClass("active");

        $("#chapter_pages").change(function(event) {
            const file = event.target.files[0].name;
            $("#chapter_pages_label").text(file);
        });
    </script>
}