NaniWeb/Controllers/SettingsManagerController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using NaniWeb.Models.Settings;
using NaniWeb.Others.Services;

namespace NaniWeb.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class SettingsManagerController : Controller
    {
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly SettingsManager _settingsManager;

        public SettingsManagerController(IWebHostEnvironment hostingEnvironment, SettingsManager settingsManager)
        {
            _hostingEnvironment = hostingEnvironment;
            _settingsManager = settingsManager;
        }

        [HttpGet]
        public IActionResult General()
        {
            var model = new GeneralForm
            {
                SiteName = _settingsManager.GetSetting("SiteName").Value,
                SiteDescription = _settingsManager.GetSetting("SiteDescription").Value,
                SiteUrl = _settingsManager.GetSetting("SiteUrl").Value,
                EnableRegistration = bool.Parse(_settingsManager.GetSetting("EnableRegistration").Value),
                NumberOfUpdatesToShow = byte.Parse(_settingsManager.GetSetting("NumberOfUpdatesToShow").Value),
                SiteFooter = _settingsManager.GetSetting("SiteFooterCode").Value,
                SiteSideBar = _settingsManager.GetSetting("SiteSideBar").Value,
                SiteAboutPage = _settingsManager.GetSetting("SiteAboutPage").Value
            };

            return View("GeneralSettings", model);
        }

        [HttpPost]
        public async Task<IActionResult> General(GeneralForm generalForm)
        {
            if (ModelState.IsValid)
            {
                var tasks = new Task[8];

                tasks[0] = Task.Run(() => _settingsManager.AddSettings("SiteName", generalForm.SiteName));
                tasks[1] = Task.Run(() => _settingsManager.AddSettings("SiteDescription", generalForm.SiteDescription));
                tasks[2] = Task.Run(() => _settingsManager.AddSettings("SiteUrl", generalForm.SiteUrl));
                tasks[3] = Task.Run(() => _settingsManager.AddSettings("EnableRegistration", generalForm.EnableRegistration.ToString()));
                tasks[4] = Task.Run(() => _settingsManager.AddSettings("NumberOfUpdatesToShow", generalForm.NumberOfUpdatesToShow.ToString()));
                tasks[5] = Task.Run(() => _settingsManager.AddSettings("SiteFooterCode", generalForm.SiteFooter ?? string.Empty));
                tasks[6] = Task.Run(() => _settingsManager.AddSettings("SiteSideBar", generalForm.SiteSideBar ?? string.Empty));
                tasks[7] = Task.Run(() => _settingsManager.AddSettings("SiteAboutPage", generalForm.SiteAboutPage ?? string.Empty));

                TempData["Error"] = false;

                await Task.WhenAll(tasks);
            }
            else
            {
                TempData["Error"] = true;
            }

            return RedirectToAction("General");
        }

        [HttpGet]
        public IActionResult Email()
        {
            var model = new EmailForm
            {
                EnableEmailRecovery = bool.Parse(_settingsManager.GetSetting("EnableEmailRecovery").Value),
                SmtpServer = _settingsManager.GetSetting("SmtpServer").Value,
                SmtpUser = _settingsManager.GetSetting("SmtpUser").Value,
                SmtpPassword = _settingsManager.GetSetting("SmtpPassword").Value,
                SiteEmail = _settingsManager.GetSetting("GroupsEmailAddress").Value,
                RecaptchaSiteKey = _settingsManager.GetSetting("RecaptchaSiteKey").Value,
                RecaptchaSecretKey = _settingsManager.GetSetting("RecaptchaSecretKey").Value
            };

            return View("EmailSettings", model);
        }

        [HttpPost]
        public async Task<IActionResult> Email(EmailForm emailForm)
        {
            var tasks = new Task[7];

            if (emailForm.EnableEmailRecovery)
            {
                if (ModelState.IsValid)
                {
                    tasks[0] = Task.Run(() => _settingsManager.AddSettings("EnableEmailRecovery", emailForm.EnableEmailRecovery.ToString()));
                    tasks[1] = Task.Run(() => _settingsManager.AddSettings("SmtpServer", emailForm.SmtpServer));
                    tasks[2] = Task.Run(() => _settingsManager.AddSettings("SmtpUser", emailForm.SmtpUser));
                    tasks[3] = Task.Run(() => _settingsManager.AddSettings("SmtpPassword", emailForm.SmtpPassword));
                    tasks[4] = Task.Run(() => _settingsManager.AddSettings("GroupsEmailAddress", emailForm.SiteEmail));
                    tasks[5] = Task.Run(() => _settingsManager.AddSettings("RecaptchaSiteKey", emailForm.RecaptchaSiteKey));
                    tasks[6] = Task.Run(() => _settingsManager.AddSettings("RecaptchaSecretKey", emailForm.RecaptchaSecretKey));

                    TempData["Error"] = false;

                    await Task.WhenAll(tasks);
                }
                else
                {
                    TempData["Error"] = true;
                }
            }
            else
            {
                tasks[0] = Task.Run(() => _settingsManager.AddSettings("EnableEmailRecovery", emailForm.EnableEmailRecovery.ToString()));
                tasks[1] = Task.Run(() => _settingsManager.AddSettings("SmtpServer", emailForm.SmtpServer ?? string.Empty));
                tasks[2] = Task.Run(() => _settingsManager.AddSettings("SmtpUser", emailForm.SmtpUser ?? string.Empty));
                tasks[3] = Task.Run(() => _settingsManager.AddSettings("SmtpPassword", emailForm.SmtpPassword ?? string.Empty));
                tasks[4] = Task.Run(() => _settingsManager.AddSettings("GroupsEmailAddress", emailForm.SiteEmail));
                tasks[5] = Task.Run(() => _settingsManager.AddSettings("RecaptchaSiteKey", emailForm.RecaptchaSiteKey));
                tasks[6] = Task.Run(() => _settingsManager.AddSettings("RecaptchaSecretKey", emailForm.RecaptchaSecretKey));

                TempData["Error"] = false;

                await Task.WhenAll(tasks);
            }

            return RedirectToAction("Email");
        }

        [HttpGet]
        public IActionResult GoogleAnalytics()
        {
            var model = new GoogleAnalyticsForm
            {
                EnableGoogleAnalytics = bool.Parse(_settingsManager.GetSetting("EnableGoogleAnalytics").Value),
                GoogleAnalyticsTrackingCode = _settingsManager.GetSetting("GoogleAnalyticsTrackingCode").Value
            };

            return View("GoogleAnalyticsSettings", model);
        }

        [HttpPost]
        public async Task<IActionResult> GoogleAnalytics(GoogleAnalyticsForm googleAnalyticsForm)
        {
            var tasks = new Task[2];

            if (googleAnalyticsForm.EnableGoogleAnalytics)
            {
                if (ModelState.IsValid)
                {
                    tasks[0] = Task.Run(() => _settingsManager.AddSettings("EnableGoogleAnalytics", googleAnalyticsForm.EnableGoogleAnalytics.ToString()));
                    tasks[1] = Task.Run(() => _settingsManager.AddSettings("GoogleAnalyticsTrackingCode", googleAnalyticsForm.GoogleAnalyticsTrackingCode));

                    TempData["Error"] = false;

                    await Task.WhenAll(tasks);
                }
                else
                {
                    TempData["Error"] = true;
                }
            }
            else
            {
                tasks[0] = Task.Run(() => _settingsManager.AddSettings("EnableGoogleAnalytics", googleAnalyticsForm.EnableGoogleAnalytics.ToString()));
                tasks[1] = Task.Run(() => _settingsManager.AddSettings("GoogleAnalyticsTrackingCode", googleAnalyticsForm.GoogleAnalyticsTrackingCode ?? string.Empty));

                TempData["Error"] = false;

                await Task.WhenAll(tasks);
            }

            return RedirectToAction("GoogleAnalytics");
        }

        [HttpGet]
        public IActionResult Disqus()
        {
            var model = new DisqusForm
            {
                EnableDisqus = bool.Parse(_settingsManager.GetSetting("EnableDisqus").Value),
                DisqusShortname = _settingsManager.GetSetting("DisqusShortname").Value
            };

            return View("DisqusSettings", model);
        }

        [HttpPost]
        public async Task<IActionResult> Disqus(DisqusForm disqusForm)
        {
            var tasks = new Task[2];

            if (disqusForm.EnableDisqus)
            {
                if (ModelState.IsValid)
                {
                    tasks[0] = Task.Run(() => _settingsManager.AddSettings("EnableDisqus", disqusForm.EnableDisqus.ToString()));
                    tasks[1] = Task.Run(() => _settingsManager.AddSettings("DisqusShortname", disqusForm.DisqusShortname));

                    TempData["Error"] = false;

                    await Task.WhenAll(tasks);
                }
                else
                {
                    TempData["Error"] = true;
                }
            }
            else
            {
                tasks[0] = Task.Run(() => _settingsManager.AddSettings("EnableDisqus", disqusForm.EnableDisqus.ToString()));
                tasks[1] = Task.Run(() => _settingsManager.AddSettings("DisqusShortname", disqusForm.DisqusShortname ?? string.Empty));

                TempData["Error"] = false;

                await Task.WhenAll(tasks);
            }

            return RedirectToAction("Disqus");
        }

        [HttpGet]
        public IActionResult Ads()
        {
            var model = new AdsForm
            {
                EnableAds = bool.Parse(_settingsManager.GetSetting("EnableAds").Value),
                AdsHeaderCode = _settingsManager.GetSetting("AdsHeaderCode").Value,

NaniWeb/Views/SettingsManager/AdsSettings.cshtml
@model AdsForm

@{
    ViewData["Title"] = "Ads - Settings";
}

<partial name="_AdminNav"/>

<div class="container mt-3">
    <div class="card bg-primary border-secondary">
        <h5 class="card-header bg-primary">Settings</h5>
        <div class="card-body">
            @if (TempData["Error"] != null && (bool) TempData["Error"])
            {
                <div class="alert alert-dismissible alert-danger">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Something went wrong. Please check your data and try again.
                </div>
            }
            else if (TempData["Error"] != null && !(bool) TempData["Error"])
            {
                <div class="alert alert-dismissible alert-success">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Settings saved successfully.
                </div>
            }
            <form id="ads_settings_form" asp-controller="SettingsManager" asp-action="Ads" novalidate>
                <fieldset>
                    <legend>Ads Settings</legend>
                    <div class="form-group">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" aria-describedby="enable_ads_help" id="enable_ads" asp-for="EnableAds"/>Enable Ads
                            </label>
                        </div>
                        <small id="enable_ads_help" class="form-text text-muted">Enable site wide ads scripts and slots.</small>
                    </div>
                    <div class="form-group">
                        <label for="ads_header_script">Ads Header Script</label>
                        <textarea class="form-control" id="ads_header_script" asp-for="AdsHeaderCode" aria-describedby="ads_header_script_help" placeholder="Ads header script" rows="10"></textarea>
                        <small id="ads_header_script_help" class="form-text text-muted">Your ads networks's header script.</small>
                    </div>
                    <div class="form-group">
                        <label for="ads_top_slot">Ads Top Slot</label>
                        <textarea class="form-control" id="ads_top_slot" asp-for="AdsLocationTop" aria-describedby="ads_top_slot_help" placeholder="Ads code" rows="10"></textarea>
                        <small id="ads_top_slot_help" class="form-text text-muted">Ads code to show in the top slot.</small>
                    </div>
                    <div class="form-group">
                        <label for="ads_middle_slot">Ads Middle Slot</label>
                        <textarea class="form-control" id="ads_middle_slot" asp-for="AdsLocationMiddle" aria-describedby="ads_middle_slot_help" placeholder="Ads code" rows="10"></textarea>
                        <small id="ads_middle_slot_help" class="form-text text-muted">Ads code to show in the middle slot.</small>
                    </div>
                    <div class="form-group">
                        <label for="ads_bottom_slot">Ads Top Slot</label>
                        <textarea class="form-control" id="ads_bottom_slot" asp-for="AdsLocationBottom" aria-describedby="ads_bottom_slot_help" placeholder="Ads code" rows="10"></textarea>
                        <small id="ads_bottom_slot_help" class="form-text text-muted">Ads code to show in the bottom slot.</small>
                    </div>
                </fieldset>
                <div>
                    <button class="btn btn-success float-right mt-3" id="submit" type="submit">Save Settings</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Body
{
    <script>
        $("#settings").addClass("active");
    </script>
}

NaniWeb/Views/SettingsManager/DisqusSettings.cshtml
@model DisqusForm

@{
    ViewData["Title"] = "Disqus - Settings";
}

<partial name="_AdminNav"/>

<div class="container mt-3">
    <div class="card bg-secondary border-light">
        <h5 class="card-header bg-secondary">Settings</h5>
        <div class="card-body">
            @if (TempData["Error"] != null && (bool) TempData["Error"])
            {
                <div class="alert alert-dismissible alert-danger">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Something went wrong. Please check your data and try again.
                </div>
            }
            else if (TempData["Error"] != null && !(bool) TempData["Error"])
            {
                <div class="alert alert-dismissible alert-success">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Settings saved successfully.
                </div>
            }
            <form id="disqus_settings_form" asp-controller="SettingsManager" asp-action="Disqus" novalidate>
                <fieldset>
                    <legend>Disqus Settings</legend>
                    <div class="form-group">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" aria-describedby="enable_disqus_help" id="enable_disqus" asp-for="EnableDisqus"/>Enable disqus
                            </label>
                        </div>
                        <small id="enable_disqus_help" class="form-text text-muted">Enable disqus forums on the project pages and on the reader.</small>
                    </div>
                    <div class="form-group">
                        <label for="disqus_shortname">Disqus Shortname</label>
                        <input class="form-control" id="disqus_shortname" asp-for="DisqusShortname" aria-describedby="disqus_shortname_help" placeholder="Disqus Shortname">
                        <small id="disqus_shortname_help" class="form-text text-muted">Your disqus forum's shortname.</small>
                    </div>
                </fieldset>
                <div>
                    <button class="btn btn-success float-right mt-3" id="submit" type="submit">Save Settings</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Body
{
    <script>
        $("#settings").addClass("active");
    </script>
}

NaniWeb/Views/SettingsManager/EmailSettings.cshtml
@model EmailForm

@{
    ViewData["Title"] = "Email - Settings";
}

<partial name="_AdminNav"/>

<div class="container mt-3">
    <div class="card bg-secondary border-light">
        <h5 class="card-header bg-secondary">Settings</h5>
        <div class="card-body">
            @if (TempData["Error"] != null && (bool) TempData["Error"])
            {
                <div class="alert alert-dismissible alert-danger">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Something went wrong. Please check your data and try again.
                </div>
            }
            else if (TempData["Error"] != null && !(bool) TempData["Error"])
            {
                <div class="alert alert-dismissible alert-success">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Settings saved successfully.
                </div>
            }
            <form id="email_settings_form" asp-controller="SettingsManager" asp-action="Email" novalidate>
                <fieldset>
                    <legend>Email Settings</legend>
                    <div class="form-group">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" aria-describedby="enable_email_recovery_help" id="enable_email_recovery" asp-for="EnableEmailRecovery"/>Enable Email
                            </label>
                        </div>
                        <small id="enable_email_recovery_help" class="form-text text-muted">This functionality enables account recovery through email. It also enable a contact form.</small>
                    </div>
                    <div class="form-group">
                        <label for="smtp_server">SMTP Server</label>
                        <input class="form-control" id="smtp_server" asp-for="SmtpServer" aria-describedby="smtp_server_help" placeholder="SMTP Server address">
                        <small id="smtp_server_help" class="form-text text-muted">The address of the SMTP server that will send the email.</small>
                    </div>
                    <div class="form-group">
                        <label for="smtp_user">SMTP User</label>
                        <input class="form-control" id="smtp_user" asp-for="SmtpUser" aria-describedby="smtp_user_help" placeholder="SMTP Server User">
                        <small id="smtp_user_help" class="form-text text-muted">The user to authenticate with the specified SMTP server.</small>
                    </div>
                    <div class="form-group">
                        <label for="smtp_password">SMTP Password</label>
                        <input class="form-control" id="smtp_password" asp-for="SmtpPassword" aria-describedby="smtp_password_help" placeholder="SMTP Server Password">
                        <small id="smtp_password_help" class="form-text text-muted">The password to authenticate with the specified SMTP server.</small>
                    </div>
                    <div class="form-group">
                        <label for="site_email">Site Email</label>
                        <input class="form-control" id="site_email" asp-for="SiteEmail" aria-describedby="site_email_help" placeholder="Email Address">
                        <small id="site_email_help" class="form-text text-muted">The destination of the messages sent through the contact form.</small>
                    </div>
                    <div class="form-group">
                        <label for="recaptcha_site_key">ReCaptcha Site Key</label>
                        <input class="form-control" id="recaptcha_site_key" asp-for="RecaptchaSiteKey" aria-describedby="recaptcha_site_key_help" placeholder="ReCaptcha Site Key">
                        <small id="recaptcha_site_key_help" class="form-text text-muted">Your site key. Settings up ReCaptcha is necessary to avoid spam through the contact form.</small>
                    </div>
                    <div class="form-group">
                        <label for="recaptcha_secret_key">ReCaptcha Secret Key</label>
                        <input class="form-control" id="recaptcha_secret_key" asp-for="RecaptchaSecretKey" aria-describedby="recaptcha_secret_key_help" placeholder="ReCaptcha Secret Key">
                        <small id="recaptcha_secret_key_help" class="form-text text-muted">Your secret key.</small>
                    </div>
                </fieldset>
                <div>
                    <button class="btn btn-success float-right mt-3" id="submit" type="submit">Save settings</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Body
{
    <script>
        $("#settings").addClass("active");
    </script>
}

NaniWeb/Views/SettingsManager/GeneralSettings.cshtml
@model GeneralForm

@{
    ViewData["Title"] = "General - Settings";
}

<partial name="_AdminNav"/>

<div class="container mt-3">
    <div class="card bg-primary border-secondary">
        <h5 class="card-header bg-primary">Settings</h5>
        <div class="card-body">
            @if (TempData["Error"] != null && (bool) TempData["Error"])
            {
                <div class="alert alert-dismissible alert-danger">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Something went wrong. Please check your data and try again.
                </div>
            }
            else if (TempData["Error"] != null && !(bool) TempData["Error"])
            {
                <div class="alert alert-dismissible alert-success">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Settings saved successfully.
                </div>
            }
            <form id="general_settings_form" asp-controller="SettingsManager" asp-action="General" novalidate>
                <fieldset>
                    <legend>General Settings</legend>
                    <div class="form-group">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" aria-describedby="enable_registration_help" id="enable_registration" asp-for="EnableRegistration"/>Enable User Registration
                            </label>
                        </div>
                        <small id="enable_registration_help" class="form-text text-muted">Allow new users to register to this website. Recommended to keep it off, only turning it on when the need arises.</small>
                    </div>
                    <div class="form-group">
                        <label for="site_name">Site Same</label>
                        <input class="form-control" id="site_name" asp-for="SiteName" aria-describedby="site_name_help" placeholder="Site Same">
                        <small id="site_name_help" class="form-text text-muted">The name of your website.</small>
                    </div>
                    <div class="form-group">
                        <label for="site_description">Site Description</label>
                        <input class="form-control" id="site_description" asp-for="SiteDescription" aria-describedby="site_description_help" placeholder="Site Description">
                        <small id="site_description_help" class="form-text text-muted">The description of your website. This will appear in search engines.</small>
                    </div>
                    <div class="form-group">
                        <label for="site_url">Site URL</label>
                        <input class="form-control" id="site_url" asp-for="SiteUrl" aria-describedby="site_url_help" placeholder="URL">
                        <small id="site_url_help" class="form-text text-muted">Your website's url without trailing slashes. ex: https://google.com, https://mangadex.org</small>
                    </div>
                    <div class="form-group">
                        <label for="site_number_updates">Number of Updates</label>
                        <input class="form-control" id="site_number_updates" asp-for="NumberOfUpdatesToShow" aria-describedby="site_number_updates_help" placeholder="Number of Updates">
                        <small id="site_number_updates_help" class="form-text text-muted">The number of update entries that you want to show on the front page. Range: 10 to 255</small>
                    </div>
                    <div class="form-group">
                        <label for="site_about">About Us Page</label>
                        <textarea class="form-control" id="site_about" asp-for="SiteAboutPage" aria-describedby="site_about_help" placeholder="About Us page's code" rows="10"></textarea>
                        <small id="site_about_help" class="form-text text-muted">Your website's 'About Us' page. The page must be written in HTML.</small>
                    </div>
                    <div class="form-group">
                        <label for="site_site_panel">Side Panel</label>
                        <textarea class="form-control" id="site_site_panel" asp-for="SiteSideBar" aria-describedby="site_site_panel_help" placeholder="Side Panel's code" rows="10"></textarea>
                        <small id="site_site_panel_help" class="form-text text-muted">Your website's side panel. This must be written in HTML.</small>
                    </div>
                    <div class="form-group">
                        <label for="site_footer">Site Footer</label>
                        <textarea class="form-control" id="site_footer" asp-for="SiteFooter" aria-describedby="site_footer_help" placeholder="Footer's code" rows="10"></textarea>
                        <small id="site_footer_help" class="form-text text-muted">Your website's footer. This must be written in HTML.</small>
                    </div>
                </fieldset>
                <div>
                    <button class="btn btn-success float-right mt-3" id="submit" type="submit">Save Settings</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Body
{
    <script>
        $("#settings").addClass("active");
    </script>
}

NaniWeb/Views/SettingsManager/GoogleAnalyticsSettings.cshtml
@model GoogleAnalyticsForm

@{
    ViewData["Title"] = "Google Analytics - Settings";
}

<partial name="_AdminNav"/>

<div class="container mt-3">
    <div class="card bg-secondary border-light">
        <h5 class="card-header bg-secondary">Settings</h5>
        <div class="card-body">
            @if (TempData["Error"] != null && (bool) TempData["Error"])
            {
                <div class="alert alert-dismissible alert-danger">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Something went wrong. Please check your data and try again.
                </div>
            }
            else if (TempData["Error"] != null && !(bool) TempData["Error"])
            {
                <div class="alert alert-dismissible alert-success">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Settings saved successfully.
                </div>
            }
            <form id="google_analytics_settings_form" asp-controller="SettingsManager" asp-action="GoogleAnalytics" novalidate>
                <fieldset>
                    <legend>Google Analytics Settings</legend>
                    <div class="form-group">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" aria-describedby="enable_google_analytics_help" id="enable_google_analytics" asp-for="EnableGoogleAnalytics"/>Enable Google Analytics
                            </label>
                        </div>
                        <small id="enable_google_analytics_help" class="form-text text-muted">Enable Google Analytics on public pages.</small>
                    </div>
                    <div class="form-group">
                        <label for="google_analytics_tracking_code">Tracking Code</label>
                        <input class="form-control" id="google_analytics_tracking_code" asp-for="GoogleAnalyticsTrackingCode" aria-describedby="google_analytics_tracking_code_help" placeholder="Tracking Code">
                        <small id="google_analytics_tracking_code_help" class="form-text text-muted">The code used by Google Analytics to identify this website.</small>
                    </div>
                </fieldset>
                <div>
                    <button class="btn btn-success float-right mt-3" id="submit" type="submit">Save Settings</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Body
{
    <script>
        $("#settings").addClass("active");
    </script>
}