NaniWeb/Controllers/OthersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NaniWeb.Data;
using NaniWeb.Models.SignIn;
using Npgsql;

namespace NaniWeb.Controllers
{
    [AllowAnonymous]
    public class OthersController : Controller
    {
        private readonly NaniWebContext _naniWebContext;
        private readonly SignInManager<IdentityUser<int>> _signInManager;
        private readonly UserManager<IdentityUser<int>> _userManager;

        public OthersController(NaniWebContext naniWebContext, SignInManager<IdentityUser<int>> signInManager, UserManager<IdentityUser<int>> userManager)
        {
            _naniWebContext = naniWebContext;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public IActionResult Error()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Install()
        {
            return _naniWebContext.Database.GetAppliedMigrations().Any() ? (IActionResult) RedirectToAction("Index", "Home") : View();
        }

        [HttpPost]
        public async Task<IActionResult> Install(SignUpForm signUpForm)
        {
            if (_naniWebContext.Database.GetAppliedMigrations().Any())
                return RedirectToAction("Index", "Home");

            if (ModelState.IsValid)
            {
                await _naniWebContext.Database.MigrateAsync();
                var npgsqlConnection = (NpgsqlConnection) _naniWebContext.Database.GetDbConnection();
                npgsqlConnection.Open();
                npgsqlConnection.ReloadTypes();

                var user = new IdentityUser<int>
                {
                    UserName = signUpForm.Username,
                    Email = signUpForm.Email,
                    EmailConfirmed = true
                };
                
                await _userManager.CreateAsync(user, signUpForm.Password);
                await _userManager.AddToRoleAsync(user, "Administrator");

                await _signInManager.PasswordSignInAsync(user, signUpForm.Password, false, false);

                return RedirectToAction("General", "SettingsManager");
            }

            TempData["Error"] = true;

            return View();
        }

        public IActionResult Denied()
        {
            return View();
        }
    }
}

NaniWeb/Views/Others/Denied.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Access denied</title>
    <link rel="stylesheet" href="~/libs/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/libs/css/site.css?v=3"/>
    <link rel="stylesheet" href="~/libs/css/login.css?v=1"/>
</head>
<body class="bg-primary text-white">
<figure class="figure text-center mx-auto">
    <img class="figure-img img-fluid" src="~/assets/denied.jpg" alt=""/>
    <figcaption class="figure-caption font-weight-normal">
        <h1 class="h5">Please contact the administrator and ask permissions.</h1>
    </figcaption>
</figure>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

NaniWeb/Views/Others/Install.cshtml
@model SignUpForm

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Install - NaniWeb</title>
    <link rel="stylesheet" href="~/libs/css/bootstrap.min.css?v=1"/>
    <link rel="stylesheet" href="~/libs/css/site.css?v=3"/>
</head>
<body class="bg-primary text-white">
<nav class="navbar navbar-light bg-light justify-content-center">
    <a class="navbar-brand" href="#">NaniWeb</a>
</nav>
<div class="container mt-3">
    <div class="card bg-primary border-secondary">
        <h5 class="card-header bg-primary">Installer</h5>
        <div class="card-body">
            @if (TempData["Error"] != null && (bool) TempData["Error"])
            {
                <div class="alert alert-dismissible alert-danger text-center">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    Something went wrong. Please check your data and try again.
                </div>
            }
            <form id="install_form" asp-controller="Others" asp-action="Install" novalidate>
                <fieldset>
                    <legend>Account Setup</legend>
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input class="form-control" id="username" asp-for="Username" aria-describedby="username_help" placeholder="Username">
                        <small id="username_help" class="form-text text-muted">Minimum of 3 characters. Alphanumeric characters and symbols are allowed.</small>
                    </div>
                    <div class="form-group">
                        <label for="email">Email Address</label>
                        <input class="form-control" id="email" asp-for="Email" aria-describedby="email_help" placeholder="Email Address">
                        <small id="email_help" class="form-text text-muted">Type the email address for your account.</small>
                    </div>
                    <div class="form-group">
                        <label for="email_confirm">Email address (again)</label>
                        <input type="email" class="form-control" id="email_confirm" aria-describedby="email_confirm_help" placeholder="Email Address">
                        <small id="email_confirm_help" class="form-text text-muted">Repeat your email address.</small>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input class="form-control" id="password" asp-for="Password" aria-describedby="password_help" placeholder="Password">
                        <small id="password_help" class="form-text text-muted">Minimum of 8 characters. Alphanumeric characters and symbols are allowed.</small>
                    </div>
                    <div class="form-group">
                        <label for="password_confirm">Password (again)</label>
                        <input type="password" class="form-control" id="password_confirm" aria-describedby="password_confirm_help" placeholder="Password">
                        <small id="password_confirm_help" class="form-text text-muted">Repeat your password.</small>
                    </div>
                </fieldset>
                <div>
                    <button class="btn btn-success float-right mt-3" id="submit" type="submit">Install</button>
                </div>
            </form>
        </div>
    </div>
</div>
<footer class="footer bg-white text-dark">
    <div class="container text-center">
        NaniWeb built by <a href="https://github.com/Dinokin">Dinokin</a>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="~/libs/js/site.js?v=2"></script>
<script>
    $("#install_form").submit(function(e) {
        const username = $("#username");
        const email = $("#email");
        const emailConfirm = $("#email_confirm");
        const password = $("#password");
        const passwordConfirm = $("#password_confirm");

        if (!validateGenericInput3Chars(username.val())) {
            username.addClass("is-invalid").focus();
            e.preventDefault(e);
            return;
        }

        if (!validateEmail(email.val())) {
            email.addClass("is-invalid").focus();
            e.preventDefault(e);
            return;
        }

        if (email.val() !== emailConfirm.val()) {
            emailConfirm.addClass("is-invalid").focus();
            e.preventDefault(e);
            return;
        }

        if (!validatePassword(password.val())) {
            password.addClass("is-invalid").focus();
            e.preventDefault(e);
            return;
        }

        if (password.val() !== passwordConfirm.val()) {
            passwordConfirm.addClass("is-invalid").focus();
            e.preventDefault(e);
            return;
        }
    });
</script>
</body>
</html>