NaniWeb/Models/Settings/GoogleAnalyticsForm.cs
using System.ComponentModel.DataAnnotations;

namespace NaniWeb.Models.Settings
{
    public class GoogleAnalyticsForm
    {
        [Required] public bool EnableGoogleAnalytics { get; set; }

        [Required] public string GoogleAnalyticsTrackingCode { get; set; }
    }
}

NaniWeb/Controllers/AnnouncementManagerController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NaniWeb.Data;
using NaniWeb.Models.Announcement;
using NaniWeb.Others;

namespace NaniWeb.Controllers
{
    [Authorize(Roles = "Administrator, Moderator")]
    public class AnnouncementManagerController : Controller
    {
        private readonly NaniWebContext _naniWebContext;

        public AnnouncementManagerController(NaniWebContext naniWebContext)
        {
            _naniWebContext = naniWebContext;
        }

        public async Task<IActionResult> List()
        {
            var announcements = await _naniWebContext.Announcements.OrderByDescending(ann => ann.PostDate).ToArrayAsync();

            ViewData["Announcements"] = announcements;

            return View("AnnouncementList");
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View("AddAnnouncement");
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddAnnouncement addAnnouncement)
        {
            if (ModelState.IsValid)
            {
                var announcement = new Announcement
                {
                    Title = addAnnouncement.Title,
                    Content = addAnnouncement.Content,
                    PostDate = DateTime.UtcNow,
                    UrlSlug = Utils.GenerateSlug(addAnnouncement.Title)
                };

                await _naniWebContext.Announcements.AddAsync(announcement);
                await _naniWebContext.SaveChangesAsync();

                return RedirectToAction("List");
            }

            TempData["Error"] = true;

            return RedirectToAction("Add");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var announcement = await _naniWebContext.Announcements.SingleAsync(ann => ann.Id == id);
            var model = new EditAnnouncement
            {
                AnnouncementId = announcement.Id,
                Title = announcement.Title,
                Content = announcement.Content
            };

            return View("EditAnnouncement", model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditAnnouncement editAnnouncement)
        {
            if (ModelState.IsValid)
            {
                var announcement = await _naniWebContext.Announcements.SingleAsync(ann => ann.Id == editAnnouncement.AnnouncementId);
                announcement.Title = editAnnouncement.Title;
                announcement.Content = editAnnouncement.Content;
                announcement.UrlSlug = Utils.GenerateSlug(editAnnouncement.Title);

                _naniWebContext.Announcements.Update(announcement);
                await _naniWebContext.SaveChangesAsync();

                return RedirectToAction("List");
            }

            TempData["Error"] = true;

            return RedirectToAction("Edit", new {id = editAnnouncement.AnnouncementId});
        }

        public async Task<IActionResult> Delete(int id)
        {
            var announcement = await _naniWebContext.Announcements.SingleAsync(ann => ann.Id == id);
            _naniWebContext.Announcements.Remove(announcement);
            await _naniWebContext.SaveChangesAsync();

            return RedirectToAction("List");
        }
    }
}

NaniWeb/Controllers/SeriesManagerController.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NaniWeb.Data;
using NaniWeb.Models.Series;
using NaniWeb.Others;

namespace NaniWeb.Controllers
{
    public class SeriesManagerController : Controller
    {
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly NaniWebContext _naniWebContext;

        public SeriesManagerController(IWebHostEnvironment hostingEnvironment, NaniWebContext naniWebContext)
        {
            _hostingEnvironment = hostingEnvironment;
            _naniWebContext = naniWebContext;
        }

        [Authorize(Roles = "Administrator, Moderator, Uploader")]
        public async Task<IActionResult> List()
        {
            var series = await _naniWebContext.Series.OrderBy(key => key.Id).ToArrayAsync();

            ViewData["Series"] = series;

            return View("SeriesList");
        }

        [HttpGet]
        [Authorize(Roles = "Administrator, Moderator")]
        public IActionResult Add()
        {
            return View("AddSeries");
        }

        [HttpPost]
        [Authorize(Roles = "Administrator, Moderator")]
        public async Task<IActionResult> Add(AddSeries addSeries)
        {
            if (ModelState.IsValid)
            {
                var series = new Series
                {
                    Name = addSeries.Name,
                    Author = addSeries.Author,
                    Artist = addSeries.Artist,
                    Synopsis = addSeries.Synopsis,
                    Type = addSeries.Type,
                    Status = addSeries.Status,
                    UrlSlug = Utils.GenerateSlug(addSeries.Name)
                };

                await _naniWebContext.Series.AddAsync(series);
                await _naniWebContext.SaveChangesAsync();

                var path = $"{_hostingEnvironment.WebRootPath}{Path.DirectorySeparatorChar}images{Path.DirectorySeparatorChar}covers{Path.DirectorySeparatorChar}{series.Id}.png";
                Directory.CreateDirectory(path.Replace($"{Path.DirectorySeparatorChar}{series.Id}.png", string.Empty));

                using (var file = System.IO.File.Create(path))
                {
                    await addSeries.Cover.CopyToAsync(file);
                }

                var fileInfo = new FileInfo(path);
                var destination = fileInfo.Directory;

                Utils.ResizeImage(fileInfo, destination, $"{series.Id}_small", 209, 300);
                Utils.ResizeImage(fileInfo, destination, $"{series.Id}_smaller", 209 / 2, 300 / 2);

                return RedirectToAction("List");
            }

            TempData["Error"] = true;

            return RedirectToAction("Add");
        }

        [HttpGet]
        [Authorize(Roles = "Administrator, Moderator")]
        public async Task<IActionResult> Edit(int id)
        {
            var series = await _naniWebContext.Series.SingleAsync(srs => srs.Id == id);

            var model = new EditSeries
            {
                SeriesId = series.Id,
                Name = series.Name,
                Author = series.Author,
                Artist = series.Artist,
                Synopsis = series.Synopsis,
                Type = series.Type,
                Status = series.Status
            };

            return View("EditSeries", model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditSeries editSeries)
        {
            if (ModelState.IsValid)
            {
                var series = await _naniWebContext.Series.SingleAsync(srs => srs.Id == editSeries.SeriesId);

                series.Name = editSeries.Name;
                series.Author = editSeries.Author;
                series.Artist = editSeries.Artist;
                series.Synopsis = editSeries.Synopsis;
                series.Type = editSeries.Type;
                series.Status = editSeries.Status;
                series.UrlSlug = Utils.GenerateSlug(editSeries.Name);

                _naniWebContext.Series.Update(series);
                await _naniWebContext.SaveChangesAsync();

                if (editSeries.Cover != null)
                {
                    var path = $"{_hostingEnvironment.WebRootPath}{Path.DirectorySeparatorChar}images{Path.DirectorySeparatorChar}covers{Path.DirectorySeparatorChar}{series.Id}.png";

                    using (var file = System.IO.File.Create(path))
                    {
                        await editSeries.Cover.CopyToAsync(file);
                    }

                    var fileInfo = new FileInfo(path);
                    var destination = fileInfo.Directory;

                    Utils.ResizeImage(fileInfo, destination, $"{series.Id}_small", 209, 300);
                    Utils.ResizeImage(fileInfo, destination, $"{series.Id}_smaller", 209 / 2, 300 / 2);
                }

                return RedirectToAction("List");
            }

            TempData["Error"] = true;

            return RedirectToAction("Edit");
        }

        [Authorize(Roles = "Administrator, Moderator")]
        public async Task<IActionResult> Delete(int id)
        {
            var coversLocation = $"{_hostingEnvironment.WebRootPath}{Path.DirectorySeparatorChar}images{Path.DirectorySeparatorChar}covers{Path.DirectorySeparatorChar}";
            var pagesLocation = $"{_hostingEnvironment.WebRootPath}{Path.DirectorySeparatorChar}images{Path.DirectorySeparatorChar}pages{Path.DirectorySeparatorChar}";
            var series = await _naniWebContext.Series.SingleAsync(srs => srs.Id == id);
            var chapters = _naniWebContext.Chapters.Where(chp => chp.Series == series).Include(chp => chp.Pages);
            var downloadsDir = Utils.CurrentDirectory.CreateSubdirectory("Downloads");

            System.IO.File.Delete($"{coversLocation}{series.Id}.png");
            System.IO.File.Delete($"{coversLocation}{series.Id}_small.png");
            System.IO.File.Delete($"{coversLocation}{series.Id}_smaller.png");

            foreach (var chapter in chapters)
            {
                var file = $"{downloadsDir.FullName}{Path.DirectorySeparatorChar}{chapter.Id}.zip";

                foreach (var page in chapter.Pages)
                    System.IO.File.Delete($"{pagesLocation}{page.Id}.png");

                System.IO.File.Delete(file);
            }

            _naniWebContext.Series.Remove(series);
            await _naniWebContext.SaveChangesAsync();

            return RedirectToAction("List");
        }
    }
}

NaniWeb/Controllers/UserManagerController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace NaniWeb.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UserManagerController : Controller
    {
        private readonly UserManager<IdentityUser<int>> _userManager;

        public UserManagerController(UserManager<IdentityUser<int>> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> List()
        {
            var users = await _userManager.Users.OrderBy(user => user.UserName).ToArrayAsync();
            var userRoleArray = new Tuple<IdentityUser<int>, string>[_userManager.Users.Count()];

            for (var i = 0; i < users.Length; i++)
            {
                var roles = await _userManager.GetRolesAsync(users[i]);
                userRoleArray[i] = new Tuple<IdentityUser<int>, string>(users[i], roles.Count > 0 ? roles[0] : "None");
            }

            ViewData["Users"] = userRoleArray;

            return View("UserList");
        }

        public async Task<IActionResult> EditRole(int userId, string role)
        {
            var user = await _userManager.FindByIdAsync(userId.ToString());
            await _userManager.RemoveFromRoleAsync(user, "Administrator");
            await _userManager.RemoveFromRoleAsync(user, "Moderator");
            await _userManager.RemoveFromRoleAsync(user, "Uploader");

            if (role != "None")
                await _userManager.AddToRoleAsync(user, role);

            return RedirectToAction("List");
        }

        public async Task<IActionResult> Delete(int userId)
        {
            var user = await _userManager.FindByIdAsync(userId.ToString());
            await _userManager.DeleteAsync(user);

            return RedirectToAction("List");
        }
    }
}

NaniWeb/Views/Shared/_AdminNav.cshtml
@inject SettingsManager SettingsManager

<nav class="navbar navbar-expand-md navbar-light bg-light">
    <a class="navbar-brand" href="@Url.Action("Index", "Home")">@SettingsManager.GetSetting("SiteName").Value</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown" id="announcements">
                <a class="nav-link dropdown-toggle" href="#" id="announcements_label" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Announcements</a>
                <div class="dropdown-menu" aria-labelledby="announcements_label">
                    <a class="dropdown-item" href="@Url.Action("Add", "AnnouncementManager")">Add Announcement</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="@Url.Action("List", "AnnouncementManager")">Announcement List</a>
                </div>
            </li>
            <li class="nav-item dropdown" id="series">
                <a class="nav-link dropdown-toggle" href="#" id="series_label" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Series</a>
                <div class="dropdown-menu" aria-labelledby="series_label">
                    <a class="dropdown-item" href="@Url.Action("Add", "SeriesManager")">Add Series</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="@Url.Action("List", "SeriesManager")">Series List</a>
                </div>
            </li>
            <li class="nav-item" id="users">
                <a class="nav-link" href="@Url.Action("List", "UserManager")">Users</a>
            </li>
            <li class="nav-item dropdown" id="settings">
                <a class="nav-link dropdown-toggle" href="#" id="settings_label" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings</a>
                <div class="dropdown-menu" aria-labelledby="settings_label">
                    <a class="dropdown-item" href="@Url.Action("General", "SettingsManager")">General</a>
                    <a class="dropdown-item" href="@Url.Action("Email", "SettingsManager")">Email</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="@Url.Action("Disqus", "SettingsManager")">Disqus</a>
                    <a class="dropdown-item" href="@Url.Action("GoogleAnalytics", "SettingsManager")">Google Analytics</a>
                    <a class="dropdown-item" href="@Url.Action("Ads", "SettingsManager")">Ads</a>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Profile")">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("SignOut", "SignIn")">Sign out</a>
            </li>
        </ul>
    </div>
</nav>

NaniWeb/Views/Shared/_AdsBody.cshtml
@inject SettingsKeeper SettingsKeeper

@if (bool.Parse(SettingsKeeper.GetSetting("EnableAds").Value) && SettingsKeeper.GetSetting("AdsBodyScripts").Value != string.Empty)
{
    @Html.Raw(SettingsKeeper.GetSetting("AdsBodyScripts").Value)
}

NaniWeb/Views/Shared/_AdsBottomSlot.cshtml
@inject SettingsManager SettingsManager

@if (ViewData["EnableAdsHere"] != null && (bool) ViewData["EnableAdsHere"])
{
    if (bool.Parse(SettingsManager.GetSetting("EnableAds").Value))
    {
        <div class="container">
            @Html.Raw(SettingsManager.GetSetting("AdsLocationBottom").Value)
        </div>
    }
}

NaniWeb/Views/Shared/_AdsContainer.cshtml
@inject SettingsKeeper SettingsKeeper

@if (bool.Parse(SettingsKeeper.GetSetting("EnableAds").Value) && SettingsKeeper.GetSetting("AdsContainerCode").Value != string.Empty)
{
    <div class="container my-2 border border-light rounded">
        @Html.Raw(SettingsKeeper.GetSetting("AdsContainerCode").Value)
    </div>
}

NaniWeb/Views/Shared/_AdsHeader.cshtml
@inject SettingsKeeper SettingsKeeper

@if (bool.Parse(SettingsKeeper.GetSetting("EnableAds").Value) && SettingsKeeper.GetSetting("AdsHeadScripts").Value != string.Empty)
{
    @Html.Raw(SettingsKeeper.GetSetting("AdsHeadScripts").Value)
}

NaniWeb/Views/Shared/_AdsHeaderCode.cshtml
@inject SettingsManager SettingsManager

@if (ViewData["EnableAdsHere"] != null && (bool) ViewData["EnableAdsHere"])
{
    if (bool.Parse(SettingsManager.GetSetting("EnableAds").Value))
    {
        <div class="container">
            @Html.Raw(SettingsManager.GetSetting("AdsHeaderCode").Value)
        </div>
    }
}

NaniWeb/Views/Shared/_AdsMiddleSlot.cshtml
@inject SettingsManager SettingsManager

@if (ViewData["EnableAdsHere"] != null && (bool) ViewData["EnableAdsHere"])
{
    if (bool.Parse(SettingsManager.GetSetting("EnableAds").Value))
    {
        if (ViewData["DisableAdsContainer"] != null && (bool) ViewData["DisableAdsContainer"])
        {
            @Html.Raw(SettingsManager.GetSetting("AdsLocationMiddle").Value)
        }
        else
        {
            <div class="container">
                @Html.Raw(SettingsManager.GetSetting("AdsLocationMiddle").Value)
            </div>
        }
    }
}

NaniWeb/Views/Shared/_AdsTopSlot.cshtml
@inject SettingsManager SettingsManager

@if (ViewData["EnableAdsHere"] != null && (bool) ViewData["EnableAdsHere"])
{
    if (bool.Parse(SettingsManager.GetSetting("EnableAds").Value))
    {
        <div class="container">
            @Html.Raw(SettingsManager.GetSetting("AdsLocationTop").Value)
        </div>
    }
}

NaniWeb/Views/Shared/_DisqusDiv.cshtml
@inject SettingsManager SettingsManager

@if (bool.Parse(SettingsManager.GetSetting("EnableDisqus").Value))
{
    <div id="disqus_thread"></div>
}

NaniWeb/Views/Shared/_DisqusScript.cshtml
@inject SettingsManager SettingsManager

@if (bool.Parse(SettingsManager.GetSetting("EnableDisqus").Value))
{
    <script>
        var disqus_config = function() {
            this.page.url = "@ViewData["DisqusUrl"]";
            this.page.identifier = "@ViewData["DisqusIdentifier"]";
            this.page.title = "@ViewData["DisqusTitle"]";
        };

        (function() {
            const d = document;
            const s = d.createElement("script");

            s.src = "https://@(SettingsManager.GetSetting("DisqusShortname").Value).disqus.com/embed.js";

            s.setAttribute("data-timestamp", +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>
}

NaniWeb/Views/Shared/_GoogleAnalytics.cshtml
@inject SettingsManager SettingsManager

@if (bool.Parse(SettingsManager.GetSetting("EnableGoogleAnalytics").Value))
{
    <script async src="https://www.googletagmanager.com/gtag/js?id=@SettingsManager.GetSetting("GoogleAnalyticsTrackingCode").Value"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() { dataLayer.push(arguments); }

        gtag("js", new Date());

        gtag("config", "@SettingsManager.GetSetting("GoogleAnalyticsTrackingCode").Value");
    </script>
}

NaniWeb/Views/Shared/_HomeNav.cshtml
@using Microsoft.AspNetCore.Identity
@inject SettingsManager SettingsManager
@inject SignInManager<IdentityUser<int>> SignInManager

<nav class="navbar navbar-expand-md navbar-light bg-light">
    <a class="navbar-brand" href="@Url.Action("Index", "Home")">@SettingsManager.GetSetting("SiteName").Value</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item" id="home">
                <a class="nav-link" href="@Url.Action("Index", "Home")">Home</a>
            </li>
            <li class="nav-item" id="announcements">
                <a class="nav-link" href="@Url.Action("Announcements", "Home")">Announcements</a>
            </li>
            <li class="nav-item" id="projects">
                <a class="nav-link" href="@Url.Action("Projects", "Home")">Projects</a>
            </li>
            <li class="nav-item" id="about">
                <a class="nav-link" href="@Url.Action("About", "Home")">About Us</a>
            </li>
            @if (bool.Parse(SettingsManager.GetSetting("EnableEmailRecovery").Value))
            {
                <li class="nav-item" id="contact">
                    <a class="nav-link" href="@Url.Action("Contact", "Home")">Contact</a>
                </li>
            }
        </ul>
        @if (SignInManager.IsSignedIn(User))
        {
            <ul class="navbar-nav">
                <li class="nav-item" id="profile">
                    <a class="nav-link" href="@Url.Action("Index", "Profile")">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("List", "SeriesManager")">Admin panel</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("SignOut", "SignIn")">Sign out</a>
                </li>
            </ul>
        }
    </div>
</nav>

NaniWeb/Views/Shared/_Layout.cshtml
@inject SettingsManager SettingsManager

@{
    ViewData["SiteName"] = SettingsManager.GetSetting("SiteName").Value;
    ViewData["SiteDescription"] = SettingsManager.GetSetting("SiteDescription").Value;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    @if (ViewData["AllowIndexing"] == null || !(bool) ViewData["AllowIndexing"])
    {
        <meta name="robots" content="noindex, nofollow">
    }
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="@ViewData["SiteDescription"]">
    <title>@ViewData["Title"]@(ViewData["TitleSeparator"] ?? " - ")@ViewData["SiteName"]</title>
    <link rel="icon" href="~/assets/icon.png">
    <link rel="stylesheet" href="~/libs/css/bootstrap.min.css?v=1"/>
    <link rel="stylesheet" href="~/libs/css/site.css?v=3"/>
    <link rel="manifest" href="/manifest.json">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <partial name="_AdsHeaderCode"/>
    <partial name="_CookieConsent"/>
    @await RenderSectionAsync("Header", false)
</head>
<body class="bg-primary text-white">
@RenderBody()
<div style="height: 100px"></div>
<partial name="_Footer"/>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="~/libs/js/site.js?v=2"></script>
@await RenderSectionAsync("Body", false)
</body>
</html>

NaniWeb/Views/Shared/_SidePanel.cshtml
@inject SettingsManager SettingsManager

<div>
    @if (!string.IsNullOrWhiteSpace(SettingsManager.GetSetting("SiteSideBar").Value))
    {
        @Html.Raw(SettingsManager.GetSetting("SiteSideBar").Value)
    }
    else
    {
        <div class="card mb-3 bg-primary border-secondary text-center">
            <h5 class="card-header bg-primary">Example</h5>
            <div class="card-body">
                Example side bar.<br/> You can edit this inside the admin panel.
            </div>
        </div>
    }
</div>